name: owili
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <5.0.0"
dependencies:
  flutter:
    sdk: flutter
  #material_design_icons_flutter: ^3.2.3895
  #cupertino_icons: ^0.1.2
  #line_icons: ^0.2.0
  flutter_icons: ^1.1.0
  fluttericon: ^2.0.0
  icofont_flutter: ^1.3.0
  #emoji_picker: ^0.1.0
  card_swiper: ^2.0.4
  provider: ^6.0.1
  emoji_picker:
    git:
      url: https://github.com/viandmarket25/emoji_picker

  hive_flutter: ^1.0.0
  hive_generator: ^1.1.0
  hive: ^2.0.4
  carousel_pro: ^1.0.0
  iconsax: ^0.0.8
  getwidget: ^2.0.4
  #iwebview_flutter: ^0.1.1
  flutter_mobile_vision: ^0.1.4+1
  http: ^0.13.5
  http_client: ^1.5.1
  http_proxy: ^1.2.0
  web_socket_channel: ^2.1.0
  flutter_unicons: ^0.0.6
  #tflite: ^1.1.2
  #tflite_flutter: ^0.8.0
  #tflite_flutter_helper: any
  #tflite_flutter_helper: ^0.2.0
  scidart: ^0.0.2-dev.4
  flutter_statusbar_text_color: ^0.1.2
  widget_animator: ^1.0.0+7
  animated_widgets: ^1.0.6
  camera: ^0.8.1
  #english_words: ^3.2.0
  google_fonts: ^2.0.0
  image_picker: ^0.7.4
  dotted_line: ^3.0.0
  flutter_map: ^0.12.0
  vibration: ^1.7.3
  flutter_staggered_grid_view: ^0.4.0
  eva_icons_flutter: ^3.0.0
  carousel_slider: ^3.0.0
  map: ^0.3.0
  responsive_framework: ^0.1.0
  tabbar: ^0.1.1
  tab_indicator_styler: ^2.0.0
  #table_calendar: ^2.3.3
  table_calendar:
    git:
      url: https://github.com/viandmarket25/table_calendar

  bruno:
    git:
      url: https://github.com/viandmarket25/bruno-english
  #camera: ^0.7.0+2
  flutter_emoji_keyboard: ^0.1.3
  location: ^2.3.5
  geolocator: ^5.3.1
  geolocation: ^1.1.2
  #pytorch_mobile: ^0.1.0
  statusbar: ^1.1.0
  network_image_to_byte: ^0.0.1
  convex_bottom_bar: ^3.0.0
  #bruno: ^3.0.0
  #tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  dartx: ^0.7.1
  path: ^1.8.0
  collection: ^1.15.0
  characters: ^1.1.0
  crypto: ^3.0.1
  path_provider: ^2.0.1
  #tuple: ^2.0.0
  #------added after adding tflite_helper package
  tuple: ^1.0.2
  quiver: ^0.22.0
  latlong: ^0.6.1
  logging: 0.11.3
  flutter_svg: 0.22.0
  path_drawing: ^0.5.0
  #

# The following section is specific to Flutter.
flutter:

  fonts:
    - family: Montserrat-Bold
      fonts:
          - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat-SemiBold
      fonts:
          - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-Medium
      fonts:
          - asset:  assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-Regular
      fonts:
          - asset:  assets/fonts/Montserrat-Regular.ttf

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    #- assets/models/
    #- assets/models/face_detection_front.tflite
    #- assets/models/mobilefacenet.tflite
    #- assets/images/face-2.jpg
    #- assets/images/product_images/
